# Generated by Django 4.1 on 2022-09-09 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Matric_no',
            new_name='regno',
        ),
    ]
